### ISSUE TITLE
Add github pre-commit

### ISSUE THREAD

**Issue by roberto910907** [hoshomoh/CSVUtils#13]
@hoshomoh I think it would be a good idea to create a git pre-commit hook file to check coding standard and code coverage before you push to the repo. So people who are contributing with this repository could know that they need to check/fix some stuff to pass some of the **required checks before merging**.

[Example](https://gist.github.com/wrseward/258cab96c73840335e5823b308c59d77)

WDYT?

**Comment by hoshomoh** [comment]
I am not a fan of git pre-commit hooks for public repositories. What we can do however, is add a make file to run the test and check on the right PHP version
