### ISSUE TITLE
Replacement typed value bug

### ISSUE THREAD

**Issue by tomas-benedikt** [hoshomoh/CSVUtils#15]
`FormatsMessages::makeReplacements` accepts `$value` as `mixed` data type, but `::replaceValuePlaceholder` accepts `$value` only as `string`, so when value comes as `NULL`, then it throw error, cause strict_types are required.

**Comment by hoshomoh** [comment]
Issue fixed and released with version [v5.0.1](https://github.com/hoshomoh/CSVUtils/releases/tag/v5.0.1)
