### ISSUE TITLE
When is support of PHP 8 planned?

### ISSUE THREAD

**Issue by bednic** [hoshomoh/CSVUtils#19]
Hi, I'm using this library and it little bit blocking me to upgrade to PHP 8, because latest stable release has unsatisfying php version condition. But in master it seems like right condition to be able used in PHP 8 platform. So can you release patch version with change?

**Comment by bednic** [comment]
@hoshomoh do you plan support this lib in a future?

**Comment by hoshomoh** [comment]
Hi @bednic sorry I have been very busy. I will do some testing over the weekend and create a patch for PHP 8

**Comment by hoshomoh** [comment]
@bednic I created a patch so you should able to use in PHP 8
