### ISSUE TITLE
Line number in error data

### ISSUE THREAD

**Issue by nlemoine** [hoshomoh/CSVUtils#5]
Hi, 

Great library, I was painfully doing validations in a much uglier way before I stumbled upon this. 

One thing is missing, I did not find an easy way to retrieve line number in errors data. Pointing the line number when errors occur is IMHO necessary to provide usable feedback to the user.

**Comment by hoshomoh** [comment]
@nlemoine thanks for the feedback. By line number you mean the line on the CSV where the error occurred right?

**Comment by nlemoine** [comment]
@hoshomoh Sorry, yes, line number of the CSV file.

**Comment by hoshomoh** [comment]
This is actually a very good feedback....I will look into this during the week

**Comment by hoshomoh** [comment]
This feature is now implemented and released with version 2.1.0. You can find more information about this release here https://github.com/hoshomoh/CSVUtils/releases/tag/v2.1.0

**Comment by nlemoine** [comment]
Thanks!
