### ISSUE TITLE
PHP7+ compatibility

### ISSUE THREAD

**Issue by roberto910907** [hoshomoh/CSVUtils#9]
@hoshomoh Hi there, what do you think if we start supporting php7+?

My suggestions are to have the master branch using php7+ features(by default if you installed this package), since there are so many people/tools using the latest version of the language. We can keep the current code(without types) as antoher branch. So if anyone out there is still using php5.6, they could be able to use a different branch.

By doing that we can increase the php required version in [ composer.json](https://github.com/hoshomoh/CSVUtils/blob/master/composer.json#L13).

**Comment by hoshomoh** [comment]
@roberto910907 feel free to open a pull request, I'm happy to review and pull it into the branch.

**Comment by roberto910907** [comment]
@hoshomoh Great, I've been waiting your :+1: to start working on this.

**Comment by hoshomoh** [comment]
Resolved and merged with version [v5.0.0](https://github.com/hoshomoh/CSVUtils/releases/tag/v5.0.0)
